### ISSUE TITLE
MacOS 11.1 load failure

### ISSUE THREAD

**Issue by ehood** [Siguza/hsp4#2] opened 2021-04-05 19:40 UTC
Hi Siguza, any reason you can think that the kext will not load on MacOS11.1?

Load attempt - 
```bash
nluus-MacBook-Air:hsp4 nluu$ sudo kextload ./net.siguza.hsp4.kext
Password:
Executing: /usr/bin/kmutil load -p /Users/nluu/hsp4/net.siguza.hsp4.kext
Error Domain=KMErrorDomain Code=71 "Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)" UserInfo={NSLocalizedDescription=Kernel request failed: (libkern/kext) kext (kmod) start/stop routine failed (-603946985)}
```
My ultimate goal is just to dump some kernel memory, with your tools.

**Comment by Siguza** [comment] 2021-04-06 03:03
It probably fails to find the `zone_map` symbol, but that doesn't matter much now.  
This kext is dead and will never support macOS 11.

The problem is that Apple introduced this check in `convert_port_to_map_with_flavor`:

```c
map = task->map;
if (map->pmap == kernel_pmap) {
	if (flavor == TASK_FLAVOR_CONTROL) {
		panic("userspace has control access to a "
		    "kernel map %p through task %p", map, task);
	}
	if (task != kernel_task) {
		panic("userspace has access to a "
		    "kernel map %p through task %p", map, task);
	}
} else {
	pmap_require(map->pmap);
}
```

This means that any use of a "counterfeit" kernel task port (like the one created by my kext) will cause a kernel panic.  
Together with `task_conversion_eval`, this leaves only one allowed case: read access via a legitimate kernel task port.

The thing is, on macOS you can already get such a task port via the `processor_set_tasks` API. As such, there is no need whatsoever for my kext to provide that, and any attempt at providing a port with read access would require code patches... at which point you can also just patch out the checks themselves, so that's moot as well.

If you're using `kmem` from ios-kern-utils, all you should have to do is replace [this macro](https://github.com/Siguza/ios-kern-utils/blob/master/src/lib/libkern.c#L59) with this:

```c
#define VERIFY_TASK(task, ret) (ret == KERN_SUCCESS)
```

If I'm ever going to revisit this, I'll write a new kext and have it publish an IOService with an API of my own design.

**Comment by Siguza** [comment] 2021-04-06 03:12
Actually going to archive this repo, so I'm closing this.  
If you need further help, feel free to open a new ticket over at [kern-utils](https://github.com/Siguza/ios-kern-utils).

**Closed as completed by Siguza** 2021-04-06 03:12 UTC
